# Generated by Django 6.0.3 on 2026-05-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_client_id_alter_commerciaux_id_alter_compte_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('type_operation', models.CharField(choices=[('retrait', 'Retrait'), ('versement', 'Versement')], max_length=20)),
                ('customer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('compte_number', models.CharField(blank=True, max_length=100, null=True)),
                ('recu_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('agence_code', models.CharField(blank=True, max_length=50, null=True)),
                ('user_code', models.CharField(blank=True, max_length=100, null=True)),
                ('working_date_day', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Opération',
                'verbose_name_plural': 'Opérations',
                'db_table': 'operations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type_operation', 'working_date_day'], name='idx_op_type_date'), models.Index(fields=['agence_code', 'working_date_day'], name='idx_op_agence_date'), models.Index(fields=['customer_code'], name='idx_op_customer')],
            },
        ),
    ]
